/**
 * @file Defines the BaseLocalExecutionContext class.
 *
 * @author Luke Chavers <luke@c2cschools.com>
 * @author Kevin Sanders <kevin@c2cschools.com>
 * @since 5.0.0
 * @license See LICENSE.md for details about licensing.
 * @copyright 2017 C2C Schools, LLC
 */

"use strict";

// Important Note
// --------------
// This module only loads a single dependency, directly, which is the
// parent class for the class defined within. This is intended to force
// dependency loading through the parent class, by way of the `$dep()`
// method, in order to centralize dependency definition and loading.

const BaseExecutionContext = require( "./BaseExecutionContext" );

/**
 * Represents an execution context whereby an endpoint is executed
 * in the local environment.
 *
 * @abstract
 * @memberOf ExecutionContext.Abstract
 * @extends ExecutionContext.BaseExecutionContext
 */
class BaseLocalExecutionContext extends BaseExecutionContext {

	/**
	 * The requestId of the current request. This getter overrides the default
	 * behavior by generating a fake requestId.
	 *
	 * @public
	 * @type {string}
	 */
	get requestId() {

		const me = this;

		return me.getConfigValue( "requestId", me._createFakeRequestId );
	}

	/**
	 * Generates a fake requestId that is prefixed with four 1's.
	 *
	 * @private
	 * @returns {string} A fake request ID.
	 */
	_createFakeRequestId() {

		const me = this;

		// Although we want to generate a valid requestId (for realism),
		// we're going to set the first block of characters to something
		// that identifies the UUID as being unusual and, further, as
		// being generated by this line of execution contexts.

		// Dependencies
		const uuidUtils = me.$dep( "util/uuid" );

		return uuidUtils.generate( "1111" );
	}

	/**
	 * Create a configuration object, suitable for this execution context,
	 * to be used when instantiating a new logger object.
	 *
	 * This method overrides the default behavior by loosening the minimum
	 * logging level to include "DEBUG" level log events in the log output.
	 *
	 * @private
	 * @param {Object} [loggerConfigOverrides] - Optional overrides for the
	 *     context's default logger configuration.
	 * @returns {Object} A plain configuration object to be passed to
	 *     the constructor of new Logger objects.
	 */
	_createLoggerConfig( loggerConfigOverrides ) {

		// For local development, we'll set the logging
		// level to '7', which will allow 'DEBUG' level messages.

		if ( loggerConfigOverrides.minLogLevel === undefined ) {

			loggerConfigOverrides.minLogLevel = 7;
		}

		return super._createLoggerConfig( loggerConfigOverrides );
	}
}

module.exports = BaseLocalExecutionContext;
